### ISSUE TITLE
extractor: detect all festival quests

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#104] opened 2020-08-29 11:24 UTC
If you enable the checkbox to display low-level quests and DISABLE the display of event quests, then low-level event quests will be displayed at a high level, although the display of event quests has been disabled.
![image](https://user-images.githubusercontent.com/24303693/91635659-e3befc00-ea02-11ea-98a0-1e3580869be6.png)

**Comment by Artur91425** [comment] 2020-08-29 17:53
this quest only displays because the low-level quests option is enabled

**Comment by shagu** [comment] 2020-08-30 12:32
The problem is, the quest you show here is not even detected as festival quest. There's no real indicator of festival quests in the databases therefore it is done by matching the levels: https://github.com/shagu/pfQuest/blob/master/database.lua#L1203

**Comment by Artur91425** [comment] 2020-08-31 16:49
@shagu, CMaNGOS has a "game_event_quest" database, which contains all the necessary information on festival quests.

**Comment by Artur91425** [comment] 2020-08-31 16:52
Also, this wiki has a gorgeous description of the entire database, you may be interested in some information.

**Comment by shagu** [comment] 2020-09-26 19:04
Fixed with 5.2.2

**Closed by shagu** 2020-09-26 19:04 UTC
Labels: enhancement
