### ISSUE TITLE
Underground Assault Quest Missing

### ISSUE THREAD

**Issue by Hiethen** [shagu/pfQuest#168] opened 2022-10-30 02:06 UTC
No quest marker appear on the map at level 15 and quest can be accepted.
https://www.wowhead.com/classic/quest=2040/underground-assault

**Comment by shagu** [comment] 2022-10-30 08:53
Did the quest "Speak with Shoni" show as completed in `/db journal`? 
Because this one is the only requirement for "Underground Assault" to show up - which it does for me.
Maybe you lost your pfQuest quest history due to a crash or something?

**Comment by Hiethen** [comment] 2022-10-30 10:04
I checked and the "Speak to Shoni" quest was not available in Iron Forge at
level 15 to accept and I had not accepted it before. Also, I haven't lost
the pfQuest quest history as I back up the whole Interface and WTF folder
daily.

**Comment by shagu** [comment] 2022-10-30 11:23
In other words, the server you play does not have a pre-quest requirement on "Speak to Shoni", even if wowhead says it should have? Does not sound like a pfQuest bug then, because pfQuest requires you to have that quest done before displaying the other.

**Comment by Hiethen** [comment] 2022-10-30 11:40
It's a good possibility since this is one the Turtle Wow server. Figured
I'd let you know just in case.

**Comment by shagu** [comment] 2022-10-30 11:45
> Figured I'd let you know just in case.
Always a good idea, thank you :)

Anyways, I'll close this one as it seems to work as intended.

**Closed by shagu** 2022-10-30 11:45 UTC
