### ISSUE TITLE
[Minimap][Nodes] Minimap Nodes don't update in 2.4.3.

### ISSUE THREAD

**Issue by Sattva-108** [shagu/pfQuest#186] opened 2023-03-21 20:32 UTC
## Description
**Object & Quest Giver** Minimap Nodes of pfQuest do not update itself right away after `/reload` or `/script ReloadUI()`
I think once i noticed them to re-appear on minimap. 

Quest completed nodes however updating after have no issue with **reload.** I can see them.
## How to reproduce
**Steps:**

1. Install **pfQuest-tbc**
2. Go to some place on TBC server where many nodes seen on minimap.
3. Write chat command `/script ReloadUI()`
4. And see if minimap nodes are there.

## Screenshot
**How it looks on map & minimap together**

![Minimap Nodes Missing](https://user-images.githubusercontent.com/74269253/226733103-eab1fe77-35dd-417e-b8b3-38ec4174e0f2.png)

**Comment by Sattva-108** [comment] 2023-03-21 20:35
I know you are not playing TBC, so i guess might take some time for you to go fix it.

If so, can you please provide some macro `/script` or `/run` command how to update them manually?
I have some new TBC server to play in 3 days, and would like to keep using pfQuest with no issue, thank you!

**Comment by shagu** [comment] 2023-03-21 21:30
Hi, Does this happen on the latest version?
Because a week ago I fixed something where nodes weren't updating.
Which version did you tested and can you please verify that all your settings have the minimap nodes enabled?

**Comment by shagu** [comment] 2023-03-21 21:32
Nevermind, i can reproduce it on 2.4.3

**Comment by shagu** [comment] 2023-03-21 21:47
Do you remember at which version this started to happen?

**Comment by shagu** [comment] 2023-03-21 21:55
As an intermediate workaround, you can run this: `/run Minimap:SetFrameLevel(1)`
There seems to be something wrong with the frame strata. The Minimap frame is sometimes above the pfQuest nodes which makes them invisible. Looks like i never noticed it as I was using pfUI when I played.

**Comment by shagu** [comment] 2023-03-21 21:59
Please try again with this commit: https://github.com/shagu/pfQuest/commit/5f4fe2f538a8270837bf35a7fd8a112f8474af85

pfQuest version: 6.8.2

**Comment by Sattva-108** [comment] 2023-03-22 11:05
Didn't even try the /run command, all good.
It is fixed with new version, thank you!

**Comment by shagu** [comment] 2023-03-22 11:50
Thanks for your response. Closing :)

**Closed by shagu** 2023-03-22 11:50 UTC
Labels: bug, tbc
