### ISSUE TITLE
Bug with EQL3 option to remove quests when completed from tracker

### ISSUE THREAD

**Issue by Cephel** [shagu/pfQuest#17] opened 2017-10-23 17:36 UTC
The aforementioned option does not update the mob tracking on the map when set to "Tracked Quests"

**Comment by Road-block** [comment] 2017-10-25 21:12
Duplicate of #12

**Comment by shagu** [comment] 2017-10-26 17:45
https://github.com/shagu/pfQuest/commit/5a3cb17040589bd2db386a0e4fda09f6bf939870

**Closed by shagu** 2017-10-26 17:45 UTC
