### ISSUE TITLE
in zhCN Client. Unable to display Quests of the Orgrimmar and Thunder Bluff 

### ISSUE THREAD

**Issue by xiaxiaohou** [shagu/pfQuest#140] opened 2021-12-21 18:08 UTC
I can not see the quest  points of Orgrimmar and thunder cliff on the map of the worldmap in zhCN Client,but in enus Client i can see the quests Exclamation points。My English is not very good, hopefully you can understand it

**Comment by xiaxiaohou** [comment] 2021-12-22 02:51
![2](https://user-images.githubusercontent.com/96493673/147027265-1e621af1-017f-4eed-bcc3-be60d299f733.png)

**Comment by xiaxiaohou** [comment] 2021-12-22 02:52
![1](https://user-images.githubusercontent.com/96493673/147027342-bd32accd-aa25-48c2-a45a-c2dace20fe67.png)
![2](https://user-images.githubusercontent.com/96493673/147027378-eda3650b-753e-41cc-b5a9-1e191a095896.png)

**Comment by shagu** [comment] 2021-12-22 11:00
I see you're using different map addons in both screenshots. Please disable all addons beside pfQuest and test it again.

**Comment by shagu** [comment] 2021-12-22 11:36
I was able to reproduce it.

**Comment by shagu** [comment] 2021-12-22 11:56
The issue is now fixed by this change:
https://github.com/shagu/pfQuest/commit/192b34d0e070ee30e5c5351b4067d48fa6d6c1c9

Which is now available as version [6.3.10](https://github.com/shagu/pfQuest/releases/tag/6.3.10).

**Closed by shagu** 2021-12-22 11:56 UTC
Labels: bug

**Comment by xiaxiaohou** [comment] 2022-02-11 03:25
I'm sorry to bother you again, your latest version has the above problem again。as version6.4。

**Comment by xiaxiaohou** [comment] 2022-02-11 03:32
> The issue is now fixed by this change: [192b34d](https://github.com/shagu/pfQuest/commit/192b34d0e070ee30e5c5351b4067d48fa6d6c1c9)
> 
> Which is now available as version [6.3.10](https://github.com/shagu/pfQuest/releases/tag/6.3.10).

Sorry to bother you again，Your latest version has the above problem again, in version 6.4.。

**Comment by shagu** [comment] 2022-02-11 11:37
> Sorry to bother you again，Your latest version has the above problem again, in version 6.4.。

Oh! I'm sorry. 

I forgot to persist the changes I made to the internal client files that are used.
It is now fixed by https://github.com/shagu/pfQuest/commit/ac98e586f5eb8d45cec380b1a550054f52899fc5 (6.4.1).
